apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    name: jobhub
  name: myapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    env: dev
    type: frontend
  type: NodePort
status:
  loadBalancer: {}
